import './globals.css';
import { Poppins } from 'next/font/google';
import Navbar from '@/components/ui/navbar';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-col min-h-full`}>
        <main className="flex-grow">{children}</main>
        <Navbar />
      </body>
    </html>
  );
}
